server: # 服务器的HTTP端口
  port: 8080 #端口


spring: #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.104.37.43:3306/test?characterEncoding=utf-8&serverTimezone=Asia/Shanghai #数据库地址和时区
    username: root # 数据库账号 测试
    password: root # 数据库密码
  redis:
    host: 100.104.37.43
    port: 6379

mybatis-plus: #数据库格式配置
  global-config:
    banner: false # 数据库启动的banner
    db-config:
      id-type: auto #id生成规则：mysql数据库id自增
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰,处理数据库“_"的字段
    auto-mapping-behavior: full #自动映射任何复杂的结果
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印数据库操作日志，可以注释关闭掉
  mapper-locations: classpath:mapper/*.xml

rocketmq:
  name-server: 100.104.37.43:9876
  producer:
    group: stock-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

